### ISSUE TITLE
No show instance for Foreign

### ISSUE THREAD

**Issue by jfilip** [purescript/purescript-foreign#13]
I would expect the output of JSON.stringify or similar, maybe?

**Comment by hdgarrood** [comment]
We have `Control.Monad.Eff.Console.Unsafe.logAny` for this now.

**Comment by codingedgar** [comment]
> 

I can't find `Control.Monad.Eff.Console.Unsafe.logAny` in Pursuit, has it been moved/renamed?

**Comment by JordanMartinez** [comment]
See https://github.com/purescript/purescript-console/issues/38

You can also locally define [`unsafeStringify`](https://pursuit.purescript.org/packages/purescript-simple-json/8.0.0/docs/Simple.JSON#v:unsafeStringify) via FFi if you're working on a JS backend.
