### ISSUE TITLE
Provide an Either newtype for choosing between alternative parses with IsForeign

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-foreign#26]
Like this, but not: https://github.com/purescript-contrib/gulp-purescript/blob/aa1b0d04f92f19f35ae6edfff14ff35d4dcf3834/src/Options.purs#L125-L127

**Comment by paf31** [comment]
Why not just use a combinator, or `<|>`?

Instances should have `toForeign` as an inverse to `read` IMO.

**Comment by garyb** [comment]
Yup, that's why I closed this! (#30 reminded me).
