### ISSUE TITLE
readInt function & IsForeign instance for Int

### ISSUE THREAD

**Issue by stkb** [purescript/purescript-foreign#27]
Now that purescript has Ints, could these be added?

(To determine whether a number is an int in javascript, ES6 will have the `Number.isInteger()` function; until then there's `n % 1 === 0`)

**Comment by paf31** [comment]
:+1: Yes I think so.

**Comment by Thimoteus** [comment]
Should this be closed? [readInt](https://github.com/purescript/purescript-foreign/blob/master/src/Data/Foreign.purs#L127-L135) and [IsForeign Int](https://github.com/purescript/purescript-foreign/blob/master/src/Data/Foreign/Class.purs#L47-L48).

**Comment by garyb** [comment]
Yep! Thanks for the reminder.
