### ISSUE TITLE
Add instances for List, Tuple and Map?

### ISSUE THREAD

**Issue by anttih** [purescript/purescript-foreign#30]
Maps could be read in from a list of pairs, using the List and Tuple IsForeign instances.

I think there should be a defacto way to read in key-value pairs somehow, but I'm not sure if they should be added to this project or to those specific libraries. I could wrap Map in a newtype, but like I said, I really think we should be able to read Maps.

**Comment by anttih** [comment]
Avoiding creating lots of dependencies here, or foreign dependency in lists, maps and tuples, maybe this warrants it's own foreign-extras library?

**Comment by garyb** [comment]
I think from previous discussions we'd kinda agreed to avoid providing default `IsForeign` instances for PureScript types. The meaning of `Foreign` currently is purely about direct safe coercion of types from Javascript - if we add instances for common PureScript types it confuses the matter a little, as it's more like a parser then.

**Comment by anttih** [comment]
Yeah, that makes sense. Maybe the answer here is use argonaut or a newtype.
