### ISSUE TITLE
Provide combinators for creating/modifying foreign data

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-foreign#31]
I find myself wanting inverses to `read`, more and more, especially now that `foreign-lens` exists.

**Comment by dvdsgl** [comment]
:+1:

I need a way to return complex PureScript values from my library to calling JavaScript code, and there's no canonical way for me to do this, from what I can tell.

**Comment by paf31** [comment]
My workaround for this has been to use arrays and records, and then call `toForeign` to turn that into a `Foreign` value. It's not ideal for various reasons though.

**Comment by puffnfresh** [comment]
I'll submit a PR for this.
