### ISSUE TITLE
Can't read from FileList

### ISSUE THREAD

**Issue by FrigoEU** [purescript/purescript-foreign#34]
Hey,

Small issue, not sure if you feel this is an error or not: When you have an element like this: <input type="file"> the element has a "files" property, that holds a FileList (https://developer.mozilla.org/en-US/docs/Web/API/FileList). You can read from this list just like any array (in JavaScript): 

     var file = document.getElementById('fileItem').files[0];

However the function isArray in Data/Foreign.js says this is not an array:

     Object.prototype.toString.call(documetn.getElementById("fileItem").files 
     -> [object FileList]

I solved this in my own project with a simple ffi import, but I thought I'd let you know.

Simon

**Comment by FrigoEU** [comment]
Upon further investigation, I'm unsure if what I said above is correct. Apologies, I'll reopen this when I'm sure there actually is a problem.

**Comment by garyb** [comment]
If it is `[object FileList]` then you probably need to define a custom read function for it, `unsafeReadTagged "FileList" :: F FileList` would do it.

**Comment by FrigoEU** [comment]
Yup, my error was that I tried to read the FileList as Array File, which is just dead wrong... I'll try it like that, thanks for the help!
