### ISSUE TITLE
isNullUndefinedOrWhiteSpace function

### ISSUE THREAD

**Issue by Andrew-Webb** [purescript/purescript-foreign#56]
Could we have a function like this?  It's the sort of thing I find very useful when string values are passed from C# / ASP.NET to the browser.

    // isNullUndefinedOrWhiteSpace :: Foreign -> Boolean
    // Test whether a foreign value is a null, undefined, empty or whitespace string (includes
    // being not a string).
    // Returns false only if the value is a string with one or more non-whitespace characters.
    function isNullUndefinedOrWhiteSpace(s) {
        if (!s) {
            return true;
        }

        if (typeof s !== 'string') {
            return true;
        }

        return s.trim().length === 0;
    }

Then presumably we could build on this with a PS function with a similar name, but of type `Foreign -> Maybe String`.

I'd be happy to submit a PR (but be prepared for this newbie's initial fumblings).

**Comment by paf31** [comment]
I think you could build this relatively easily in a library, using the functions provided by `purescript-foreign`.

**Comment by Andrew-Webb** [comment]
... not as addition to `purescript-foreign`... okey doke.

I built the JS function and the PS function as I described them in an 'Infrastructure' module in my PureScript project (my first)... it was instructive and fun.  The `Foreign` type is a useful type to know about.
