### ISSUE TITLE
Two Foreign examples give 404 on Pursuit

### ISSUE THREAD

**Issue by gspia** [purescript/purescript-foreign#64]
The example section of Foreign package on [Pursuit](https://pursuit.purescript.org/packages/purescript-foreign/4.0.0) has old (?) links:

_Simple Types_ link refers to JSONSimpleTypes.purs and _Arrays_ link refers to JSONArrays.purs.

The example dir has SimpleTypes.purs and Arrays.purs.

**Comment by garyb** [comment]
Could you re-open this on the Pursuit repo? It pulls in the README to produce that page, so it seems it's cached an old version or something.

**Comment by gspia** [comment]
Ok, I'll try to do it
