### ISSUE TITLE
PureScript 0.12.0 - Bower: ECONFLICT Unable to find suitable version for purescript-prelude

### ISSUE THREAD

**Issue by rouanvd** [purescript/purescript-foreign#70]
After the release of PureScript 0.12.0 a new version of the Prelude was released: 4.0.0.
The purescript-foreign package cannot be used with the new version of the Prelude yet.

Regards
--Rouan

**Comment by garyb** [comment]
This will be resolved in the next few hours, I'm making release for all the libraries at the moment.
